### ISSUE TITLE
[新功能]Rsock 断开后连接自动恢复的问题

### ISSUE THREAD

**Issue by david9991** [iceonsun/rsock#3]
之前 #1 太长，另启一个 topic。

**Comment by david9991** [comment]
是不是可以做成如果尝试连接失败就失败退出，这样我也可以用 launchd KeepAlive 让它自动重启。因为 rsock 可能绑定了设备，如果不能运行时自动重置的话，不如异常退出让用户来选择后续的重置行为？或通过一个选项来选择是退出还是继续尝试恢复？

**Comment by david9991** [comment]
我这倒是可以做到 health check 失败脚本主动重启 rsock。但我想 rsock 这个软件本身如果能有什么自主恢复的手段更好的。XD

**Comment by iceonsun** [comment]
可以另外增加一个选项，允许用户指定重试n次（n默认无限次），超过这个阈值就退出。

这个算新功能，得等我找到工作后再弄。目前先专注改被发现的bug

**Comment by iceonsun** [comment]
这个版本引入了自动重连。网络变换的情况下也能重连。

https://github.com/iceonsun/rsock/releases/tag/v2.0
