### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by xiazuojie** [iceonsun/rsock#5]
Please add support for FreeBSD

**Comment by iceonsun** [comment]
移植到freebsd上并不困难。上午我已经尝试编译出freebsd二进制（需要修改部分代码）。

主要的痛点是我是在mac上开发，没找到合适的交叉编译的工具。网上也没有支持freebsd的ci。

下个版本我会修改部分代码和编译指南。有需要的可以自己在freebsd上编译。

**Comment by iceonsun** [comment]
https://github.com/iceonsun/rsock/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97#freebsd

编译ok了把这个关了。

顺便问一句，我digitalocean创建freebsd，ifconfig只输出vetxx和lo0, 没有外网网卡，没有外网ip，但能连外网
